### PR TITLE
Draco float vertices / texture coords

### PR DESCRIPTION
**Pull request by jstys92**

### CODE REVIEW

**Comment by svensht2** [comment]
👍

**Comment by nbcong** [comment]
Hope you all are well :-)!
Willing to hear/update/demo for the current results of teleporter!
Have you done with history color based on per face/triangle texture instead of per vertex?

**Comment by zelonght** [comment]
Yup, me too, hope you guys are doing well.

**Comment by zelonght** [comment]
@svensht2 did you finish in making use of synthetics data/sequences in test framework/testing?

**Pull request merged**
